name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm install

      - name: 빌드
        run: npm run build

      - name: 중간 확인
        run: |
          ls
          echo "dist 폴더 내부 파일 목록:"
          cd dist
          ls

      - name: AWS Resource에 접근할 수 있게 AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3 기존 파일 삭제 후 빌드된 파일 업로드
        run: |
          aws s3 rm s3://${{ secrets.AWS_BUCKET_NAME }} --recursive
          aws s3 cp dist s3://${{ secrets.AWS_BUCKET_NAME }}/ --recursive

      - name: CloudFront 캐시 무효화
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
